apiVersion: v1
kind: Service
metadata:
  name: sentrasite-service
spec:
  type: NodePort
  selector:
    app: sentrasite-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP