pipeline {
    agent any
    environment {
        DOCKERHUB_USERNAME = "prvinsm21"
    }
    stages {
        stage ('Git Checkout') {
            steps {
                sh 'echo Passed'
            }
        }
        stage ('Code Compile') {
            steps {
                sh 'cd Resturant-Website && mvn clean compile'
            }
        }
        stage ('Unit Testing') {
            steps {
                sh 'cd Resturant-Website && mvn test'
            }
        }
        stage ('Integration Testing') {
            steps {
                sh 'cd Resturant-Website  && mvn verify -DskipUnitTests'
            }
        }
        stage ('Build Stage') {
            steps {
                sh 'cd Resturant-Website  && mvn clean install'
            }
        }
        stage('OWASP Dependency Check') {
            steps {
               dependencyCheck additionalArguments: '', odcInstallation: 'DP'
                    dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
                    retire-js-dependency_scanning:
                         after_script:
                            - retire --verbose

            }
        }
        stage ('Static Code analysis') {
            steps {
                script {
                    withSonarQubeEnv(credentialsId: 'sonar-api') {
                        sh 'cd Resturant-Website && mvn clean package sonar:sonar'
                    }
                }
            }
        }
        stage ('Quality Gate Status') {
            steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-api'
                }
            }
        }
    }
}